config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'activities#index'
  resources :activities do
    patch :finish
    patch :resume
    get :tags, on: :collection
  end

  resource :smartwatch do
    get :activities
    get :analytics
    patch :finish
    patch :resume
    patch :start_activity
  end

  get '/analytics' => 'analytics#index'
  get '/change_layout' => 'smartwatches#change_layout'
end

app/models/activity.rb
class Activity < ActiveRecord::Base

  acts_as_taggable

  has_many :time_ranges

  after_create :set_started_at

  scope :finished, -> { joins(:time_ranges).where('time_ranges.finished_at IS NOT NULL') }
  scope :unfinished, -> { joins(:time_ranges).where('time_ranges.finished_at IS NULL') }

  def as_json(options={})
    super(only: [ :name, :started_at, :finished_at, :notes ])
  end

  def duration
    self.time_ranges.finished.map(&:duration).sum
  end

  def finished?
    self.time_ranges.unfinished.empty?
  end

  def finish!
    self.time_ranges.unfinished.first.try :finish!
  end

  def started_at
    self.time_ranges.order('started_at ASC').first.try :started_at
  end

  def finished_at
    self.time_ranges.order('finished_at DESC').first.try :finished_at if finished?
  end

  def resume!
    self.time_ranges.create if finished?
  end

  private

  def set_started_at
    self.time_ranges.create
  end
end

app/models/time_range.rb
class TimeRange < ActiveRecord::Base

  belongs_to :activity

  before_create :set_started_at

  scope :unfinished, -> { where(finished_at: nil) }
  scope :finished, -> { where('finished_at IS NOT NULL') }

  def finished?
    finished_at?
  end

  def finish!
    update_attribute(:finished_at, DateTime.now) unless finished_at
  end

  def duration
    finished_at - started_at if finished?
  end

  private

  def set_started_at
    self.started_at = DateTime.now
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :authenticate_user!

  def index
    @activities = current_user.activities.order(:created_at)
    @activities = @activities.tagged_with(params[:q]) if params[:q].present?
  end

  def new
    create
  end

  def create
    @activity = current_user.activities.create
    redirect_to edit_activity_path(@activity)
  end

  def edit
    @activity = current_user.activities.find_by_id params[:id]
  end

  def update
    @activity = current_user.activities.find_by_id params[:id]
    @activity.update_attributes activity_params
    render json: { redirect_to: activities_path }
  end

  def destroy
    @activity = current_user.activities.find_by_id params[:id]
    @activity.destroy! if @activity
    render json: { redirect_to: activities_path }
  end

  def finish
    @activity = current_user.activities.find_by_id params[:activity_id]
    @activity.finish!
    render json: { redirect_to: activities_path }
  end

  def resume
    @activity = current_user.activities.find_by_id params[:activity_id]
    @activity.resume!
    render json: { redirect_to: activities_path }
  end

  def tags
    @tags = ActsAsTaggableOn::Tag.where("tags.name ILIKE ?", "%#{params[:term]}%")
    respond_to do |format|
      format.json do
        render json: @tags.collect{ |t| { id: t.id, label: t.name, value: t.name } }
      end
    end
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :notes, :tag_list)
  end

end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController

  before_action :authenticate_user!

  def index
    @activities = current_user.activities.finished
    @tags = @activities.map(&:tag_list).flatten.uniq
    @data = []
    @tags.each do |tag|
      @data << {
        tag: tag,
        value: @activities.tagged_with(tag).map(&:duration).sum,
        color: "rgba(#{(rand*255).to_i}, #{(rand*255).to_i}, #{(rand*255).to_i}, 1)"
      }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/smartwatches_controller.rb
class SmartwatchesController < ActionController::Base

  layout 'smartwatch'
  before_action :authenticate_user!

  def show
    @activity = current_user.activities.unfinished.last
  end

  def finish
    @activity = current_user.activities.unfinished.find_by_id(params[:id]).finish!
    render json: { redirect_to: smartwatch_path }
  end

  def resume
    @activity = current_user.activities.find_by_id(params[:id]).resume!
    render json: { redirect_to: smartwatch_path }
  end

  def activities
    @activities = current_user.activities.order('created_at desc')
  end

  def analytics
    @activities = current_user.activities.finished
    @tags = @activities.map(&:tag_list).flatten.uniq
    @data = []
    @tags.each do |tag|
      @data << {
        tag: tag,
        value: @activities.tagged_with(tag).map(&:duration).sum,
        color: "rgba(#{(rand*255).to_i}, #{(rand*255).to_i}, #{(rand*255).to_i}, 1)"
      }
    end
  end

  def start_activity
    current_user.activities.create name: params[:tag], tag_list: params[:tag]
    render json: { redirect_to: smartwatch_path }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/edit.html.haml
.row
  %h1.page-header Track Activity
  = form_for @activity, html: { method: :patch, remote: true } do |f|
    .form-group
      = f.label :name
      %br/
      = f.text_field :name, class: 'form-control', 'data-attribute' => 'name'
    .form-group
      = label_tag :notes
      %br/
      = f.text_area :notes, class: 'form-control', 'data-attribute' => 'notes'
    .form-group
      = label_tag :tags
      %br/
      = f.autocomplete_field :tag_list, tags_activities_path, class: 'form-control'
    .form-group
      = f.submit 'Save', class: 'btn btn-primary'

app/views/activities/index.html.haml
.row
  %h1.page-header Overview
  %table.table.table-hover
    %thead
      %tr
        %th #
        %th Name
        %th.hidden-xs Tagged
        %th.visible-lg Started at
        %th.visible-lg Finished at
        %th Duration
        %th.hidden-xs Note
        %th Finish
        %th Delete
    %tbody
      - @activities.each_with_index do |activity, i|
        %tr
          %td= i+1
          %td= link_to activity.name, edit_activity_path(activity)
          %td.hidden-xs= activity.tag_list
          %td.visible-lg= l(activity.started_at)
          %td.visible-lg= l(activity.finished_at) if activity.finished_at
          %td
            - if activity.finished?
              = Time.at(activity.duration).utc.strftime("%H:%M:%S")
          %td.hidden-xs= activity.notes
          %td
            - unless activity.finished_at
              = link_to activity_finish_path(activity), method: :patch, remote: :true do
                %i.glyphicon.glyphicon-pause
            - else
              = link_to activity_resume_path(activity),method: :patch, remote: :true do
                %i.glyphicon.glyphicon-play
          %td
            = link_to activity_path(activity), method: :delete, remote: true do
              %i.glyphicon.glyphicon-remove

app/views/analytics/index.html.haml
.row
  %h1.page-header Your Activities
  %canvas#canvas.pull-left{ width: '300', height: '300'}

  %ul.list-group.pull-left
    - @data.each do |datum|
      %li.list-group-item{ style: "background-color: #{datum[:color].gsub('1)', '0.4)')}; color: #{datum[:color]}" }
        = datum[:tag]
        \-
        = Time.at(datum[:value]).utc.strftime("%H:%M:%S")

:coffee
  $ ->
    data = #{@data.to_json}
    options = {}
    new Chart($("#canvas").get(0).getContext("2d")).Pie(data,options);

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TimeTracker
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui' }
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body

    #flash-messages
      - if flash[:notice]
        %p.alert.alert-info.notice
          %button{ type: "button", class: "close", "data-dismiss" => "alert", "aria-hidden" => "true" } &times;
          =notice
      - if flash[:alert]
        %p.alert.alert-danger
          %button{ type: "button", class: "close", "data-dismiss" => "alert", "aria-hidden" => "true" } &times;
          =alert

    .navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "TimeTracker", root_path, class: 'navbar-brand'
        .navbar-collapse.collapse
          - if current_user
            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to "Track Activity", new_activity_path
              %li.visible-xs
                = link_to 'Analytics', analytics_path
              %li
                = link_to 'Smartwatch', smartwatch_path
              %li
                = link_to "Log Out", destroy_user_session_path, method: :delete
          - else
            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to "Sign in", new_user_session_path
              %li
                = link_to "Sign Up", new_user_registration_path
          = form_tag activities_path, class: 'navbar-form navbar-right', method: :get do
            = text_field_tag :q, params[:q], placeholder: "Search...", class: 'form-control'
    .container-fluid
      .row
        .col-sm-3.col-md-2.sidebar
          - if current_user
            %ul.nav.nav-sidebar
              %li{ class: "#{'active' if request.fullpath == activities_path}" }
                = link_to 'Overview', activities_path
              %li{ class: "#{'active' if request.fullpath == analytics_path}" }
                = link_to 'Analytics', analytics_path
        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          = yield

app/views/layouts/smartwatch.html.haml
!!!
%html
  %head
    %title TimeTracker
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui' }
    = stylesheet_link_tag    'smartwatch', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body#body
    #smartwatch
      .navbar.navbar-default.navbar-fixed-top{role: "navigation"}
        .container-fluid
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to "♥", smartwatch_path, class: 'navbar-brand'
          .navbar-collapse.collapse
            %ul.nav.navbar-nav.navbar-right
              %li= link_to 'Show all', activities_smartwatch_path
              %li= link_to 'Analytics', analytics_smartwatch_path
              - current_user.activities.map(&:tag_list).flatten.uniq.each do |tag|
                %li
                  = link_to start_activity_smartwatch_path(tag: tag), method: :patch, remote: true do
                    %span.text-success Start:
                    = tag

      #content
        = yield

app/views/smartwatches/activities.html.haml
%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item
      .clearfix
        %strong.pull-left= activity.tag_list || activity.name || 'unknown'
        .pull-right
          - if activity.finished?
            = link_to resume_smartwatch_path(id: activity), class: 'btn btn-primary', remote: true, method: :patch do
              %i.glyphicon.glyphicon-play
          - else
            = link_to finish_smartwatch_path(id: activity), class: 'btn btn-danger', remote: true, method: :patch do
              %i.glyphicon.glyphicon-pause
      .clearfix
        Duration:
        = Time.at(activity.duration).utc.strftime("%H:%M:%S")
        Started:
        = l(activity.started_at, format: :short)
        Stopped:
        = l(activity.finished_at, format: :short) if activity.finished?

app/views/smartwatches/analytics.html.haml
.row
  %ul.list-group
    %li.list-group-item
      Total Time:
      = Time.at(@activities.map(&:duration).sum).utc.strftime("%H:%M:%S")

.row
  .col-xs-12
    %canvas#canvas{ width: '125', height: '125', style: 'margin-left: 25px;'}
    %ul.list-group
      - @data.each do |datum|
        %li.list-group-item{ style: "background-color: #{datum[:color].gsub('1)', '0.4)')}; color: #{datum[:color]}" }
          %span.tag-ellipsis= datum[:tag]
          \-
          = Time.at(datum[:value]).utc.strftime("%H:%M:%S")

:coffee
  renderData = ->
    if $("#canvas").length > 0
      data = #{@data.to_json}
      options = {}
      $("#canvas").width(125)
      $("#canvas").height(125)
      new Chart($("#canvas").get(0).getContext("2d")).Pie(data,options);
  $(document).on 'page:load', renderData
  interval = setInterval ->
    if renderData
      renderData()
      clearInterval(interval)
  , 100

app/views/smartwatches/show.html.haml
- if @activity
  %center
    %h4
      = @activity.name || 'noname'
      %br
      %small since:
      %br
      = time_ago_in_words @activity.started_at
    = link_to finish_smartwatch_path(id: @activity), class: 'btn btn-danger', method: :patch, remote: true do
      %i.glyphicon.glyphicon-pause
- else
  %center
    %h3
      No running activity. Start one, dude!

.arrows
  .left-arrow
    \<
  .right-arrow
    \>
:coffee
  $ ->
    el = document.getElementById('body')
    Hammer(el).on 'swipeleft', (event) ->
      console.log 'swipeleft'
      Turbolinks.visit "#{analytics_smartwatch_path}"
    Hammer(el).on 'swiperight', (event) ->
      console.log 'swiperight'
      Turbolinks.visit "#{activities_smartwatch_path}"